---
output: github_document
---

<!-- front_page_notes.md is generated from front_page_notes.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "front_page_notes-"
)
```


# FACkit GUI

Running `r packageDescription("FACkit", fields="Package")`, a `r packageDescription("FACkit", fields="Title")`, version `r packageVersion("FACkit")` developed by `r packageDescription("FACkit", fields="Author")`. 

## Introduction

This GUI was developed to enable intuitive and streamlined exploration and analysis of high-dimension FACS data using tSNE.

Documentation and explanation of the tools and steps used are either located beside each box or can be accessed by clicking "help" buttons.

In the event of crashes or unexpected behaviour please contact the package developer; `r packageDescription("FACkit", fields="Maintainer")`.

# VERSION NEWS

## FACkit 0.1.3

* Modified shiny app data input method to use rhandsontables instead of DT - much easier/quicker to input.
* Improved marker name sanitization

## FACkit 0.1.2

* Added Marker name sanitizing function to the shiny app
* Removed the `NEWS.md` file integration (it wasn't working)

## FACkit 0.1.1

* Increased App Upload Limit to 100 Mb
* Removed app loading of ggalt (for server purposes) and switched instances of geom_bkde to geom_density 

## FACkit 0.1.0

* Added a `NEWS.md` file to track changes to the package.
* Added documentation to FACkit GUI.
