# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
NULL

binclust2 <- function(binmat, rowids) {
    .Call('_FACkit_binclust2', PACKAGE = 'FACkit', binmat, rowids)
}

#' @export
NULL

bindist <- function(binmat, data) {
    .Call('_FACkit_bindist', PACKAGE = 'FACkit', binmat, data)
}

bingrow <- function(dthresh, minpts, data, lmarkers, oldbins, ndist, nlist, growfact) {
    .Call('_FACkit_bingrow', PACKAGE = 'FACkit', dthresh, minpts, data, lmarkers, oldbins, ndist, nlist, growfact)
}

#' Location of Skew Normal Distribution
#' @export
NULL

snlocation <- function(markdat) {
    .Call('_FACkit_snlocation', PACKAGE = 'FACkit', markdat)
}

