# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bindist <- function(binmat, data) {
    .Call(`_FACkit_bindist`, binmat, data)
}

bingrow <- function(dthresh, minpts, data, lmarkers, oldbins, ndist, nlist, growfact) {
    .Call(`_FACkit_bingrow`, dthresh, minpts, data, lmarkers, oldbins, ndist, nlist, growfact)
}

